### ISSUE TITLE
biliup标签疑似被判定为违规

### ISSUE THREAD

**Issue by JokerQyou** [ForgQi/biliup-app#25]
视频被打回后仅删除此单个标签即可过审。根据与b站客服的沟通，客服认为此标签“涉及违规网站的域名”，“如果有疑问的话可以联系网警或其他有关部门进行确认”。
我理解作者这个标签是用来统计的。可否确认一下解决方案？（是增加选项去除这个标签还是其他方案）

**Comment by ddaodan** [comment]
> 您的稿件未能通过审核。原因：（tag）含有不适宜词条或具有争议性，请修改。如有疑问请通过稿件申诉进行反馈
建议移除或者更换一个别的？

**Comment by JokerQyou** [comment]
新版已经换成了 `biliup-app`，我再观察几天。

**Comment by JokerQyou** [comment]
新版本没有再出现了。
