### ISSUE TITLE
投稿编辑功能

### ISSUE THREAD

**Issue by ddaodan** [ForgQi/biliup-app#3]
我已经有视频投稿了，可不可以加一个编辑投稿的功能，直接修改投稿
就是新增分p

**Comment by ForgQi** [comment]
理论上可以，客户端好像有这个api

**Comment by toorich** [comment]
> 我已经有视频投稿了，可不可以加一个编辑投稿的功能，直接修改投稿 就是新增分p

同需要该功能

**Comment by ForgQi** [comment]
增加了稿件编辑的功能，新建模板时填写av或BV号即可
