### ISSUE TITLE
删除初始模板后关闭重新打开，用户变成null

### ISSUE THREAD

**Issue by Pioooooo** [ForgQi/biliup-app#30]
![图片](https://user-images.githubusercontent.com/25563691/171069802-09219975-1bcf-46e1-9094-4d702f97f3bd.png)
复现步骤：登录、删除未命名模板、关闭软件、重新打开

删除config.yaml后重新打开可以修复

**Comment by luckycat0426** [comment]
感谢反馈，已设置成最后一个模板不允许删除
