### ISSUE TITLE
账号会掉，然后又要重新登录

### ISSUE THREAD

**Issue by jzfzzzz** [ForgQi/biliup-app#34]
就是那个扫码登录之后，没过几天账号就会显示null，然后必须删除配置文件，关掉软件再打开重新登录才行，这个很麻烦啊，希望作者大大能解决一下

**Comment by ForgQi** [comment]
这个情况是怎么发生的，是长时间运行吗，期间没有关闭过软件

**Comment by jzfzzzz** [comment]
刚开始有这种情况，现在好像没有了⊙∀⊙……



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 下午4:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ForgQi/biliup-app] 账号会掉，然后又要重新登录 (Issue #34)




 
这个情况是怎么发生的，是长时间运行吗，期间没有关闭过软件
