### ISSUE TITLE
上传进度超出100%

### ISSUE THREAD

**Issue by hoshinohikari** [ForgQi/biliup-app#36]
在上传视频的时候，好几次进度条超出了100%，大概到了接近120%的时候又会回到100%，这个时候才是真的上传完了。
不定期复现，复现条件不确定

**Comment by hoshinohikari** [comment]
![image](https://user-images.githubusercontent.com/23255180/174485152-4ea6b75b-080c-42e9-8497-e6483a49c2e2.png)
附加图

**Comment by RedDouu** [comment]
![image](https://user-images.githubusercontent.com/60962801/175118226-5b738be2-d104-48fa-88ec-6d1879b97c80.png)
我也遇到了同样的情况，现在是128%并且还在增加。也不知道什么时候才算是真的上传完了。

**Comment by ForgQi** [comment]
目前可以先直接点提交，在上传完成之后应该会自动提交
