### ISSUE TITLE
请问绑定国外手机号是无法使用吗

### ISSUE THREAD

**Issue by MOJI7632** [ForgQi/biliup-app#43]

**Comment by ForgQi** [comment]
用扫码或者浏览器登录

**Comment by MOJI7632** [comment]
扫码登录会这样报错…
ResponseData { code: 0, data: Value( Object({ "access_token": String( "99c51fca534be75e16c8946dee274871", ), "cookie_info": Object({ "cookies": Array([ Object({ "expires": Number( 1672826158, ), "http_only": Number( 1, ), "name": String( "SESSDATA", ), "value": String( "a985f855%2C1672826158%2C3a2dce71", ), }), Object({ "expires": Number( 1672826158, ), "http_only": Number( 0, ), "name": String( "bili_jct", ), "value": String( "0a7ed162f87f7ba0005d4413a3c2117e", ), }), Object({ "expires": Number( 1672826158, ), "http_only": Number( 0, ), "name": String( "DedeUserID", ), "value": String( "3461562859784221", ), }), Object({ "expires": Number( 1672826158, ), "http_only": Number( 0, ), "name": String( "DedeUserID__ckMd5", ), "value": String( "1186d228098896de", ), }), Object({ "expires": Number( 1672826158, ), "http_only": Number( 0, ), "name": String( "sid", ), "value": String( "q0foi455", ), }), ]), "domains": Array([ String( ".bilibili.com", ), String( ".biligame.com", ), String( ".bigfun.cn", ), String( ".bigfunapp.cn", ), String( ".dreamcast.hk", ), ]), }), "expires_in": Number( 15552000, ), "is_new": Bool( false, ), "mid": Number( 3461562859784221, ), "refresh_token": String( "eab4058721fa577fc1c549b7ee8f1c71", ), "sso": Array([ String( "https://passport.bilibili.com/api/v2/sso", ), String( "https://passport.biligame.com/api/v2/sso", ), String( "https://passport.bigfunapp.cn/api/v2/sso", ), ]), "token_info": Object({ "access_token": String( "99c51fca534be75e16c8946dee274871", ), "expires_in": Number( 15552000, ), "mid": Number( 3461562859784221, ), "refresh_token": String( "eab4058721fa577fc1c549b7ee8f1c71", ), }), }), ), message: "0", ttl: 1, }
浏览器登录也是显示登陆成功但没有跳转

**Comment by luckycat0426** [comment]
> 扫码登录会这样报错…
> 
> 浏览器登录也是显示登陆成功但没有跳转

大概知道了具体错误发生原因，回复包含b站私密信息，我先删了，请问每次登陆都是这个报错吗

**Comment by MOJI7632** [comment]
> > 扫码登录会这样报错…
> > 浏览器登录也是显示登陆成功但没有跳转
> 
> 大概知道了具体错误发生原因，回复包含b站私密信息，我先删了，请问每次登陆都是这个报错吗

是的(＞＜)

**Comment by ForgQi** [comment]
最新版有一个debug版本的包，可以试试，会有比较详细的日志

**Comment by MOJI7632** [comment]
是直接运行debug版吗 试了下扫码还是会这样报错…
ResponseData { code: 0, data: Value( Object({ "access_token": String( "809104f78553d48be50bbd6819048871", ), "cookie_info": Object({ "cookies": Array([ Object({ "expires": Number( 1673612389, ), "http_only": Number( 1, ), "name": String( "SESSDATA", ), "value": String( "b3184f22%2C1673612389%2Cae644b71", ), }), Object({ "expires": Number( 1673612389, ), "http_only": Number( 0, ), "name": String( "bili_jct", ), "value": String( "5891be7920990a55957b7e9533969caa", ), }), Object({ "expires": Number( 1673612389, ), "http_only": Number( 0, ), "name": String( "DedeUserID", ), "value": String( "3461562859784221", ), }), Object({ "expires": Number( 1673612389, ), "http_only": Number( 0, ), "name": String( "DedeUserID__ckMd5", ), "value": String( "1186d228098896de", ), }), Object({ "expires": Number( 1673612389, ), "http_only": Number( 0, ), "name": String( "sid", ), "value": String( "o4poi6kb", ), }), ]), "domains": Array([ String( ".bilibili.com", ), String( ".biligame.com", ), String( ".bigfun.cn", ), String( ".bigfunapp.cn", ), String( ".dreamcast.hk", ), ]), }), "expires_in": Number( 15552000, ), "is_new": Bool( false, ), "mid": Number( 3461562859784221, ), "refresh_token": String( "083d4c0dc16fc5e904fea1f89ae6af71", ), "sso": Array([ String( "https://passport.bilibili.com/api/v2/sso", ), String( "https://passport.biligame.com/api/v2/sso", ), String( "https://passport.bigfunapp.cn/api/v2/sso", ), ]), "token_info": Object({ "access_token": String( "809104f78553d48be50bbd6819048871", ), "expires_in": Number( 15552000, ), "mid": Number( 3461562859784221, ), "refresh_token": String( "083d4c0dc16fc5e904fea1f89ae6af71", ), }), }), ), message: "0", ttl: 1, }

**Comment by ForgQi** [comment]
再试一下v0.3.5版

**Comment by MOJI7632** [comment]
可以了！非常感谢！！
