### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by Sakuma-Rei** [ForgQi/biliup-app#69]
![image](https://user-images.githubusercontent.com/55101422/220037191-1ffbd198-56cc-497a-b20e-0baa148cc4d2.png)
默认存的模板比如这样 如果我刚打开去改标题 直接去打字打不了（）比如先打个别的什么数字才能正常打字
然后是上传 有时候中途断网了就彻底断了 不会自己再度连接 也没有按钮供你再次连接 只能把传到一半和后面没传的挨个删掉再点一遍 特别麻烦（）希望这个也能批量编辑 现在主播下播貌似容易生成1mb的文件 这能自动舍弃不传吗 卡大小之类的
不过都做到这种地步了增加易用性要不要考虑添加一个自动改日期的设定（ 就把标题的日期自动改成当天什么的 这样就能每天简单手动选一下文件直接上传了 我是按每天新建新文件夹设定的录播 这部分不知道能不能也能做成功能添加进去 新的一天开启自动传前一天的（当然我还没有仔细看过全自动化教程 主要是好像目前这些全自动化都需要安装另外的东西以及使用命令行（）总之主要是第一段的问题 最近经常转码失败orz

**Comment by ForgQi** [comment]
你有些指的是biliup的问题吗，建议在那边反馈

**Comment by Sakuma-Rei** [comment]
> 你有些指的是biliup的问题吗，建议在那边反馈
对啊 难道不是这里吗……

**Comment by Sakuma-Rei** [comment]
是说加电报吗
